name: Lint TS (eslint, prettier)

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint TS (eslint, prettier)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

     steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: '. --ext .js,.jsx,.ts,.tsx'


   
